#!/bin/sh /etc/rc.common

START=19
STOP=89

start() {
	mkdir -p /etc/nanopi-control /tmp/nanopi-control
	/usr/libexec/nanopi-control/detect-storage >/dev/null 2>&1
	rm -f /tmp/luci-indexcache
}

reload() {
	start
}
